accent = "#9393c3"
cursor = "#868f7b"
foreground = "#868f7b"
background = "#051A2B"
selection_foreground = "#868f7b"
selection_background = "#9393c3"

color0 = "#051A2B"
color1 = "#b27575"
color2 = "#80b780"
color3 = "#bdbd89"
color4 = "#9393c3"
color5 = "#ae6fae"
color6 = "#7cb6b6"
color7 = "#f9bc8a"
color8 = "#4c5641"
color9 = "#d5aeae"
color10 = "#b9dab9"
color11 = "#dfdfc3"
color12 = "#cdcde5"
color13 = "#c482c4"
color14 = "#90cbcb"
color15 = "#868f7b"
